
# This is an autogenerated file from lava/setup.py.
PANDA_SRC_PATH := /home/user/Desktop/lava/panda/panda
PANDA_BUILD_DIR := /home/user/Desktop/lava/panda/panda/build

# This is an autogenerated file from lava/setup.py.
LLVM_SRC_PATH := /llvm-3.6.2
LLVM_BUILD_PATH := /llvm-3.6.2
LLVM_BIN_PATH := $(LLVM_BUILD_PATH)/install/bin
